frr version 10.2
frr defaults traditional
hostname r2
service integrated-vtysh-config
!
interface lo
 ip address 198.51.100.2/32
!
interface eth1
 ip address 192.0.2.2/30
!
interface eth2
 ip address 192.0.2.9/30
!
line vty
!
