frr version 10.2
frr defaults traditional
hostname r3
service integrated-vtysh-config
!
interface lo
 ip address 198.51.100.3/32
!
interface eth1
 ip address 192.0.2.6/30
!
interface eth2
 ip address 192.0.2.13/30
!
line vty
!
